### ISSUE TITLE
Sampling per one application

### ISSUE THREAD

**Issue by josepdcs** [Granulate/gprofiler#298]
Hi!
Congratulations for a great work. 

I have a question: As I was able to understand, gProfiler samples whole cpu and collects metrics for all applications running inside. Is it possible just collect samples for one application, the this one that a I want to profile?

Redards!

**Comment by Jongy** [comment]
Hi @josepdcs , thanks!

As you correctly understood, gProfiler works system wide and profiles all processes. We currently don't provide any mean to filter applications to profile: we profile the entire system with `perf`, and individual runtime processes with their respective profiler (e.g Java processes with async-profiler).

We could add filtering. Could you please explain the rationale behind it? For example, if the rationale is that you only want to view the profiles of a specific application, then I'd direct you to use the filtering that the Granulate Performance Studio provides; for example, you can view the flamegraph per k8s deployment / container.

The reason we profile the entire system is that it's most convenient for the user (you don't need to configure anything) & it gives you the system-wide / cluster-wide picture of which application.

**Comment by Jongy** [comment]
> An example could be the roles: I don't want that anyone than me is able to profile my application.

gProfiler requires high privileges on the machine where it runs (many profilers that we use such as `perf`, `PyPerf` require that). So in any case, it is able to profile all processes due to its high privileges.

It is possible to run gProfiler in lower privilege mode, but it won't be able to use some of the profilers. For this use case, you can, for example, run gProfiler in the container of your application, and it will profile just your one application in the container. As an example, this is how we [run gProfiler on Fargate](https://github.com/Granulate/gprofiler#running-on-an-aws-fargate-service).

> Other example could be: I want to be able to choice whose applications/Pods will be profiled.

I see, but why do you care? Let it profile everything, and use the UI to filter the profiling data from the Pods you wish to investigate.

I am not against adding filtering in the agent, I just think that in most cases, it is easier to profile all and use the UI to filter :) 
This is similar to the request in https://github.com/Granulate/gprofiler/issues/274 . What would be the interface you'd expect for filter? It could be, for example, a filter by container name: `--container-filter='.*myapp.*'` which would be a regex matching the container/pod name, and we'd profile just them containers?
