### ISSUE TITLE
get_fs_offset and get_stack_offset not working inside of docker container

### ISSUE THREAD

**Issue by aaronweissler** [Granulate/gprofiler#443]
Hi :)

I'm testing PyPerf and wanted to run it inside of a Docker container, however running `get_fs_offset` or `get_stack_offset` there lead to the following errors:

```
root@ab6a5f8a0b76:/app# gprofiler/resources/python/pyperf/get_stack_offset  
libbpf: failed to determine tracepoint 'syscalls/sys_enter_write' perf event ID: No such file or directory  
libbpf: prog 'do_write': failed to create tracepoint 'syscalls/sys_enter_write' perf event: No such file or directory  
libbpf: failed to auto-attach program 'do_write': -2  
failed to attach BPF program: -2
```

```
root@ab6a5f8a0b76:/app# gprofiler/resources/python/pyperf/get_fs_offset   
libbpf: failed to determine tracepoint 'syscalls/sys_enter_arch_prctl' perf event ID: No such file or directory  
libbpf: prog 'do_arch_prctl': failed to create tracepoint 'syscalls/sys_enter_arch_prctl' perf event: No such file or directory  
libbpf: failed to auto-attach program 'do_arch_prctl': -2  
failed to attach BPF program: -2
```

I am running the container in privileged mode and those two outputs are actually from trying it with the gProfiler image, because I wondered if it might be some issue with how I built my own image. If I understand your implementation correctly, this should work since it is where it would be run when using the Docker way to run gProfiler too, right?
So, since it does not work with your image either, it seems like my issue is somewhere else.

I'm running all of this on Ubuntu 22.04, where locally both of the tools work just fine, and or what it's worth PyPerf itself runs just fine both locally and inside of the container..

Related question, what do those offsets depend on? I.e. are they the same between my local Ubuntu 22.04 and running a Docker container with an image that is also based on Ubuntu 22.04? 
Because if that is the case I could just run my tests with the values hardcoded in the container based on the results from running the tools locally for now.

Thank you in advance for your help and best wishes,
Aaron

**Comment by aaronweissler** [comment]
Actually, I have to correct one of my statements. When running PyPerf from inside of the container, it starts normally, but it always collects zero samples. So if you have any idea why that might be happening, any  help with that would be great too.

This is its output with `-v` set.

```
INFO:root:/PyPerf --fs-offset 5224 --stack-offset 32 -d 20 -F 99 -v 5 -p 7
container  | Profiling Sample Frequency: 99
container  | Profiling Duration: 20s
container  | 2022-08-21 19:01:17,831 Starting Bokeh server version 2.4.3 (running on Tornado 6.1)
container  | 2022-08-21 19:01:17,832 User authentication hooks NOT provided (default user enabled)
container  | 2022-08-21 19:01:17,834 Bokeh app running at: http://localhost:5006
container  | 2022-08-21 19:01:17,834 Starting Bokeh server with process id: 7
container  | prog tag mismatch bcbaaeebbccf5bae 1
container  | WARNING: cannot get prog tag, ignore saving source with program tag
container  | prog tag mismatch 6f8090bbfdfdf4b7 1
container  | WARNING: cannot get prog tag, ignore saving source with program tag
container  | Ready to profile
container  | prog tag mismatch d92d522a8ae0b133 1
container  | WARNING: cannot get prog tag, ignore saving source with program tag
container  | Attached to profiling event
container  | Started polling Perf Buffer
container  | Pruning dead pids
container  | Populating pid table
container  | Detected Python version: 3.10.4
container  | [     1] /usr/bin/python3.10 @ 0x000055e2447a9000
container  | [     1] _PyRuntime @ 0x000055e244d4ad00
container  | [     7] /usr/bin/python3.10 @ 0x0000565311ef6000
container  | [     7] _PyRuntime @ 0x0000565312497d00
container  | [     8] Process does not contain Python library
container  | Pruning dead pids
container  | Populating pid table
container  | [     8] Process does not contain Python library
container  | Profiling duration finished
container  | Detached from profiling event
container  | Draining remaining samples
container  | Finished draining remaining samples
container  | Total 0 unique Python symbols
container  | 0 samples collected
container  | 0 samples lost
container  | 0 samples with truncated stack
container  | 0 Python symbol errors
container  | 0 times Python symbol lost
container  | 0 kernel stack errors
container  | 0 native stack errors
container  | 0 errors
```

**Comment by Jongy** [comment]
Hi @aaronweissler :) I'll answers your questions one at a time.

> I am running the container in privileged mode and those two outputs are actually from trying it with the gProfiler image, because I wondered if it might be some issue with how I built my own image. If I understand your implementation correctly, this should work since it is where it would be run when using the Docker way to run gProfiler too, right?

Your assumption is correct, but the thing is, gProfiler itself makes some modifications to the execution environment to prepare it for bpf programs. See: https://github.com/Granulate/gprofiler/blob/410a61c4bf23a6854e63a80f560338b28bd61768/gprofiler/profilers/python.py#L338-L351

The error you're getting for both programs is because debugfs is not mounted, and libbpf tries to access files in this fs, e.g `/sys/kernel/debug/tracing/events/syscalls/sys_enter_arch_prctl/id`. When gProfiler starts, it ensures the fs is mounted.

If you get those errors when *gProfiler* invokes the helper programs - that's another problem, please let me know. gProfiler should prepare the environment for them, and you should not be seeing this error.

> Related question, what do those offsets depend on? I.e. are they the same between my local Ubuntu 22.04 and running a Docker container with an image that is also based on Ubuntu 22.04?

Those offsets depend on your kernel build. They will be the same for machines running the same kernel build (and they will be the same for containers running on those machines, because containers are running under the same kernel).

> Actually, I have to correct one of my statements. When running PyPerf from inside of the container, it starts normally, but it always collects zero samples. So if you have any idea why that might be happening, any help with that would be great too.

I see that you're invoking PyPerf with `-p 7`. I figure `7` is the NSpid of your Python application. While PyPerf runs in the PID namespace of your app ("in the container"), the bpf side of PyPerf runs in the kernel, and our code does not accommodate container PIDs - it expects to work with host PIDs. So this lookup always fails:
https://github.com/Granulate/bcc/blob/2c991423e7b20d36a3bda3ff9393967c87139227/examples/cpp/pyperf/PyPerfBPFProgram.cc#L287-L292

PyPerf must run in host PID NS because it needs to correlate the PIDs that its usermode part sees and the PIDs that the kernel side sees. You can run the container with `--pid=host`, or otherwise you can fix PyPerf's code to support handling of NSpids.

But the purpose of gProfiler is to hide all these complexities I described in my answers here :sweat_smile: So may I ask what is the reason you wish to use PyPerf directly and not via gProfiler? Is it a feature missing in gProfiler that we could implement?

**Comment by aaronweissler** [comment]
Hi @Jongy :)

Thank you very much for answering all of my questions!

> If you get those errors when gProfiler invokes the helper programs - that's another problem, please let me know. gProfiler should prepare the environment for them, and you should not be seeing this error.

I had tried out gProfiler with the container version once too, that worked just fine :)

> I see that you're invoking PyPerf with -p 7. I figure 7 is the NSpid of your Python application. While PyPerf runs in the PID namespace of your app ("in the container"), the bpf side of PyPerf runs in the kernel, and our code does not accommodate container PIDs - it expects to work with host PIDs. So this lookup always fails:
https://github.com/Granulate/bcc/blob/2c991423e7b20d36a3bda3ff9393967c87139227/examples/cpp/pyperf/PyPerfBPFProgram.cc#L287-L292

Yes, it's the PID of the Docker container's PID namespace. That makes sense then.

> But the purpose of gProfiler is to hide all these complexities I described in my answers here 😅 So may I ask what is the reason you wish to use PyPerf directly and not via gProfiler? Is it a feature missing in gProfiler that we could implement?

Tbh, I just found PyPerf itself first and then felt using gProfiler to profile only one specific Python process would be overkill, because I understood it, concerning Pyperf, as pretty much a wrapper to profile the full system with additionally support for multiple languages and the web application, but maybe it would actually be worth it with complexities like this existing 😄

**Comment by Jongy** [comment]
Glad it helped.

> Tbh, I just found PyPerf itself first and then felt using gProfiler to profile only one specific Python process would be overkill, because I understood it, concerning Pyperf, as pretty much a wrapper to profile the full system with additionally support for multiple languages and the web application, but maybe it would actually be worth it with complexities like this existing :smile:

Indeed, that's our way of thinking as well :) The only "bad" side effect of system-wide profiling while you just need a single proceess/app, is the extra overhead which itself is small anyway. You can disable other profilers with `--no-perf --no-java ...` and we're contemplating on adding a way to filter profiled processes as well, but currently that's not available.

**Comment by Jongy** [comment]
@aaronweissler , we added a check in https://github.com/Granulate/gprofiler/pull/456 to ensure PyPerf runs only in init PID NS, this would catch such use cases in the future :)
