### ISSUE TITLE
Different image tags in script and test fixtures

### ISSUE THREAD

**Issue by kwisniewski98** [Granulate/gprofiler#492]
Tag of gprofiler image defaults to `granulate/gprofiler` in [copy_resource_from_image.sh](https://github.com/Granulate/gprofiler/blob/master/scripts/copy_resources_from_image.sh#L8), but tests expects it to be [gprofiler](https://github.com/Granulate/gprofiler/blob/master/tests/conftest.py#L183). It's just minor inconvenience, that can be overcame providing argument to `copy_resource_from_image.sh` script, but I think it would be nice to have it standardized.

It might be also good idea to provide default value for tag in image building scripts.

**Comment by Jongy** [comment]
The reasoning is -
* `copy_resources_from_image.sh` is meant to be used during development process, e.g to get the latest builds of the resources - so from the latest image (`granulate/gprofiler:latest`).
* `gprofiler_docker_image` is used during the CI - we build the image but don't tag it as `granulate/gprofiler:latest` because it's just a CI image, it's not going to be published. That's built [here](https://github.com/Granulate/gprofiler/blob/4bcb3aedae1c286d3058a0dc0f559cf88fe5e940/.github/workflows/build-container-and-test.yml#L45).

In which flow did you encounter it? When running tests locally, the fixture expected the image but it wasn't found?

> It might be also good idea to provide default value for tag in image building scripts.

Yes. If your flow was the tests flow - I suppose we could swap the defaults - change the build scripts to build `-t gprofiler` by default, and have the fixture use it, and during publish we will pass `-t granulate/gprofiler:latest`.

**Comment by kwisniewski98** [comment]
> In which flow did you encounter it? When running tests locally, the fixture expected the image but it wasn't found?

Yes, that was the case

If there is a reason behind this, I think we can close this issue

**Comment by Jongy** [comment]
We will change the default of `build_x86_64_container.sh` to tag the image as `gprofiler` - this way the tests can copy from it.

During deploy we'll pass the deploy tag.
