### ISSUE TITLE
nodejs: perf.map attach: Allow 2 running processes in the same net namespace

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#497]
If port is already opened it won't open. We can have one of two solutions for having multiple node processes in same network namespace:

1.  Close debugger after generating perf maps and starting it each time we want to do any operation on debugger. In this method no two debuggers will be open at the same time. This will also be useful when someone started container with i. e. `--network=host`. (I've started implementing that)
2.  We can change debug port, but that can only be done inside process (we need to change `process.debugPort`). This means we need to start it on port 9229 anyway, then change `debugPort` and restart debugger.

In both methods we have to start it at 9229 port and I didn't find any solution for that.

Answering your other questions:
If module is already loaded, CDP request will respond with False when loading module
I'll add this sanity check

_Originally posted by @kwisniewski98 in https://github.com/Granulate/gprofiler/pull/451#discussion_r979972958_

**Comment by kwisniewski98** [comment]
I'm thinking it should be done this way:

1. Open debugger and connect to it, like it is done now.
2. Do what should be done with `replMode: true`, this way changes should stay even when debugger is closed.
3. Close debugger port executing `process._debugEnd()` via `Runtime.evaluate`

Alternately it can be done like that:

1. Open debugger and connect to it, like it is done now.
2. Change debugger port via executing `process.debugPort=<some_number>` via `Runtime.evaluate`. This way we can leave debugger port open.

I'm worried that second way will cause problems when we restart gProfiler, since we won't know at which port debugger is running.
